version: '3'
services:
  # ---------------------------
  # WEB
  # ---------------------------
  web:
    container_name: web
    build:
      context:  ./conf/php-apache
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./project:/app

  # ---------------------------
  # DATABASE
  # ---------------------------
  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  # ---------------------------
  # PHPMYADMIN
  # ---------------------------
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8080:80"
#    links:
#      - database:database
