version: '3'
services:
  # ---------------------------
  # WEB
  # http://127.0.0.1:8000
  # ---------------------------
  web:
    container_name: web
    build:
      context:  ./conf/php-apache
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./project:/app

  # ---------------------------
  # DATABASE
  # ---------------------------
  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  # ---------------------------
  # PHPMYADMIN
  # http://127.0.0.1:8085
  # ---------------------------
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8085:80"
    links:
      - database:db

  # ---------------------------
  # MAILER
  # http://127.0.0.1:8025
  # ---------------------------
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
