version: '3'
services:
  apache:
    build: ./
    ports:
      - 8000:80
    volumes:
      - ./project:/app
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./.env
    ports:
      - "3306:3306"
