#!/bin/bash
#encoding=utf8

set -e

# get the absolute path of the command (following the symlink) and get into it
infrapath=$(dirname $([ -L $0 ] && readlink $0 || echo $0))
cd $infrapath
infrapath=`pwd`

# Run Docker command
__docker() {
  args=$@
  cd "${infrapath}"

  if [ "$args" = "up" ]; then
    args="up -d" # Run up has detached mode.
    [ -d "src/sitm/.symfony" ] && rm -rf "src/sitm/.symfony" # Prevent from sitm is already running error.
  elif [ "$args" = "up -it" ]; then
    args="up" # Run up has interactive mode.
  elif [ "$args" = "restart" ]; then
    docker-compose stop
    args="up -d"
  elif [ "$args" = "restart -it" ]; then
    docker-compose stop
    args="up"
  fi

  docker-compose $args
}

case $@ in
    up*|stop*|down*|kill*)
        __docker $@
        ;;
    *)
esac
exit 0